### ISSUE TITLE
KeyError: 'GroupFree3DMHA is already registered in attention'

### ISSUE THREAD

**Issue by wansdd** [AIR-THU/DAIR-V2X#94]
HI, I met some touble about demo.After I install these required packges,when I run this command'bash scripts/eval_lidar_late_fusion_pointpillars.sh 0 late_fusion 2 0 100',
the error is :
Traceback (most recent call last):
  File "eval.py", line 20, in <module>
    from models import SUPPROTED_MODELS
  File "/Programs/DAIR-V2X/v2x/models/__init__.py", line 8, in <module>
    from detection_models import *
  File "../v2x/models/detection_models/__init__.py", line 2, in <module>
    from mmdet3d_anymodel_anymodality_nofusion import *
  File "../v2x/models/detection_models/mmdet3d_anymodel_anymodality_nofusion.py", line 9, in <module>
    from model_utils import init_model, inference_detector, inference_mono_3d_detector
  File "../mmdetection3d/mmdet3d/models/model_utils/__init__.py", line 2, in <module>
    from .transformer import GroupFree3DMHA
  File "../mmdetection3d/mmdet3d/models/model_utils/transformer.py", line 8, in <module>
    class GroupFree3DMHA(MultiheadAttention):
  File "/opt/conda/lib/python3.7/site-packages/mmcv/utils/registry.py", line 312, in _register
    module_class=cls, module_name=name, force=force)
  File "/opt/conda/lib/python3.7/site-packages/mmcv/utils/registry.py", line 246, in _register_module
    raise KeyError(f'{name} is already registered '
KeyError: 'GroupFree3DMHA is already registered in attention'

my packges installed is followed:
 root@8e871bc99514:/Programs/DAIR-V2X/v2x# pip list|grep mm
mmcv-full               1.3.14              
mmdet                   2.17.0              /mmdetection              
mmdet3d                 0.17.1              /mmdetection/mmdetection3d
mmsegmentation          0.14.1              
root@8e871bc99514:/Programs/DAIR-V2X/v2x# pip list|grep torch
torch                   1.6.0               
torchvision             0.7.0

**Comment by Uchan1996** [comment]
I have the same issue.
How did you solve it?
